In [65]:
import pickle

pickle.dump(model, open('heart_disease_model.pkl', 'wb'))
pickle.dump(scaler, open('scaler.pkl', 'wb'))

In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [30]:
df = pd.read_csv('D:\data\Cd\ML\KNN\disease_prediction.csv')

In [31]:
df.head()

   patient_id  age  gender  ...  physical_activity  family_history  disease
0           1   32    Male  ...                Low             Yes      Yes
1           2   31    Male  ...                Low             Yes      Yes
2           3   45    Male  ...                Low              No       No
3           4   75  Female  ...             Medium              No      Yes
4           5   53    Male  ...                Low             Yes      Yes

[5 rows x 14 columns]

In [32]:
df.tail()

     patient_id  age  gender  ...  physical_activity  family_history  disease
995         996   24    Male  ...             Medium              No       No
996         997   40    Male  ...             Medium              No       No
997         998   44  Female  ...                Low              No      Yes
998         999   31    Male  ...             Medium             Yes       No
999        1000   83    Male  ...               High              No      Yes

[5 rows x 14 columns]

In [33]:
df.shape

(1000, 14)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           1000 non-null   int64
 1   age                  1000 non-null   int64
 2   gender               1000 non-null   object
 3   glucose_mg_dl        1000 non-null   int64
 4   cholesterol_mg_dl    1000 non-null   int64
 5   systolic_bp          1000 non-null   int64
 6   diastolic_bp         1000 non-null   int64
 7   bmi                  1000 non-null   float64
 8   heart_rate           1000 non-null   int64
 9   smoking              1000 non-null   object
 10  alcohol_consumption  1000 non-null   object
 11  physical_activity    1000 non-null   object
 12  family_history       1000 non-null   object
 13  disease              1000 non-null   object
dtypes: float64(1), int64(7), object(6)
memory usage: 109.5+ KB

In [35]:
df.describe()

        patient_id          age  ...          bmi   heart_rate
count  1000.000000  1000.000000  ...  1000.000000  1000.000000
mean    500.500000    51.190000  ...    26.093000    75.968000
std     288.819436    19.847514  ...     4.758282     9.902982
min       1.000000    18.000000  ...    16.000000    47.000000
25%     250.750000    33.000000  ...    22.900000    70.000000
50%     500.500000    52.500000  ...    26.000000    76.000000
75%     750.250000    69.000000  ...    29.300000    83.000000
max    1000.000000    85.000000  ...    41.500000   114.000000

[8 rows x 8 columns]

In [36]:
df.columns

Index(['patient_id', 'age', 'gender', 'glucose_mg_dl', 'cholesterol_mg_dl',
       'systolic_bp', 'diastolic_bp', 'bmi', 'heart_rate', 'smoking',
       'alcohol_consumption', 'physical_activity', 'family_history',
       'disease'],
      dtype='object')

In [37]:
df.isnull().sum()

patient_id             0
age                    0
gender                 0
glucose_mg_dl          0
cholesterol_mg_dl      0
systolic_bp            0
diastolic_bp           0
bmi                    0
heart_rate             0
smoking                0
alcohol_consumption    0
physical_activity      0
family_history         0
disease                0
dtype: int64

Categorical Analyis

In [38]:
df.head()

   patient_id  age  gender  ...  physical_activity  family_history  disease
0           1   32    Male  ...                Low             Yes      Yes
1           2   31    Male  ...                Low             Yes      Yes
2           3   45    Male  ...                Low              No       No
3           4   75  Female  ...             Medium              No      Yes
4           5   53    Male  ...                Low             Yes      Yes

[5 rows x 14 columns]

In [39]:
df = pd.get_dummies(
    df,
 columns=['physical_activity']
)
drop_first=True

In [40]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
cols=[
'gender',
'smoking',
'alcohol_consumption',
'family_history',
'disease'
]
for col in cols:
    df[col]=le.fit_transform(df[col])

In [41]:
df.astype('int64')

     patient_id  age  ...  physical_activity_Low  physical_activity_Medium
0             1   32  ...                      1                         0
1             2   31  ...                      1                         0
2             3   45  ...                      1                         0
3             4   75  ...                      0                         1
4             5   53  ...                      1                         0
..          ...  ...  ...                    ...                       ...
995         996   24  ...                      0                         1
996         997   40  ...                      0                         1
997         998   44  ...                      1                         0
998         999   31  ...                      0                         1
999        1000   83  ...                      0                         0

[1000 rows x 16 columns]

In [42]:
df.head()

   patient_id  age  ...  physical_activity_Low  physical_activity_Medium
0           1   32  ...                   True                     False
1           2   31  ...                   True                     False
2           3   45  ...                   True                     False
3           4   75  ...                  False                      True
4           5   53  ...                   True                     False

[5 rows x 16 columns]

Index(['patient_id', 'age', 'gender', 'glucose_mg_dl', 'cholesterol_mg_dl',
       'systolic_bp', 'diastolic_bp', 'bmi', 'heart_rate', 'smoking',
       'alcohol_consumption', 'family_history', 'disease',
       'physical_activity_High', 'physical_activity_Low',
       'physical_activity_Medium'],
      dtype='object')

In [45]:
df.rename(columns={'disease':'heart_disease'}, inplace=True)

In [47]:
X=df.drop('heart_disease',axis=1)
y=df['heart_disease']

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [49]:

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [51]:
X_train_scaler=scaler.fit_transform(X_train)
X_train_scaler

array([[-1.61897442,  1.56325888,  0.9900495 , ...,  1.3971505 ,
        -0.66832224, -0.73783572],
       [ 0.12989037,  0.46850493,  0.9900495 , ...,  1.3971505 ,
        -0.66832224, -0.73783572],
       [ 0.68289109,  1.56325888, -1.0100505 , ..., -0.71574251,
         1.4962842 , -0.73783572],
       ...,
       [ 1.25317309, -1.42243372,  0.9900495 , ...,  1.3971505 ,
        -0.66832224, -0.73783572],
       [-0.21573509,  0.12017413,  0.9900495 , ...,  1.3971505 ,
        -0.66832224, -0.73783572],
       [-1.36666784, -0.12863359, -1.0100505 , ..., -0.71574251,
        -0.66832224,  1.35531525]], shape=(800, 15))

In [53]:
X_test_scaler=scaler.transform(X_test)
X_test_scaler

array([[ 0.0815028 , -0.42720285,  0.9900495 , ..., -0.71574251,
         1.4962842 , -0.73783572],
       [ 0.82805378,  0.3192203 , -1.0100505 , ...,  1.3971505 ,
        -0.66832224, -0.73783572],
       [ 0.83842254, -0.57648748, -1.0100505 , ...,  1.3971505 ,
        -0.66832224, -0.73783572],
       ...,
       [-1.00030486, -0.32767976,  0.9900495 , ..., -0.71574251,
         1.4962842 , -0.73783572],
       [ 0.39947822,  0.86659728, -1.0100505 , ...,  1.3971505 ,
        -0.66832224, -0.73783572],
       [-1.44961795,  1.51349734, -1.0100505 , ..., -0.71574251,
        -0.66832224,  1.35531525]], shape=(200, 15))

In [56]:
model=KNeighborsClassifier(n_neighbors=5)
model.fit(X_train_scaler,y_train)

KNeighborsClassifier()

In [57]:
y_pred=model.predict(X_test_scaler)

In [59]:
accuracy_score(y_test, y_pred)

0.825

In [61]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
#83 and 75 were correctly predicted as 0 and 1 respectively and 20 and 22 were incorrectly predicted as 0 and 1 respectively
#type 2 error= 20 and type 1 error=22

confusion_matrix(y_test, y_pred)

array([[91, 14],
       [21, 74]])

In [63]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.87      0.84       105
           1       0.84      0.78      0.81        95

    accuracy                           0.82       200
   macro avg       0.83      0.82      0.82       200
weighted avg       0.83      0.82      0.82       200